version: '3'
services:
  app:
    container_name: reddit-daily-report
    restart: always
    build: .
    ports:
      - '9000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  test:
    container_name: test
    restart: always
    build: .
    links: 
      - mongo